language: r
cache: packages

r_github_packages:
  - jimhester/covr
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_github hadley/devtools
  - ./travis-tool.sh install_github braverock/factorAnalytics
  - ./travis-tool.sh install_github jimhester/covr
after_success:
  - Rscript -e 'covr::coveralls()'
