language: r
cache: packages
sudo: required

warnings_are_errors: false

env:
  global:
    - NOT_CRAN=true
    
before_install: echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

env:
 global:
  - CRAN: http://cran.rstudio.com

  
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh github_package hadley/memoise
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_github hadley/devtools
  - ./travis-tool.sh install_github hadley/testthat
  - ./travis-tool.sh install_github braverock/factorAnalytics
  - ./travis-tool.sh install_github jimhester/covr
after_success:
  - Rscript -e 'covr::coveralls()'
